commit_message: 'chore: New translations %original_file_name%
append_commit_message: false
files:
  - source: /docs/**/*
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%'
  - source: /i18n/en/docusaurus-plugin-content-docs/current.json
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/%original_file_name%'
