pull_request_title: '[ci skip] New Crowdin translations'
commit_message: '[ci skip] New translations %fileName% (%languageName%)'
append_commit_message: false
files:
  - source: /docs/**/*
    translation: '/i18n/%two_letters_code%/docusaurus-plugin-content-docs/current/**/%original_file_name%'
